![pandas.jpg]()

In [ ]:
import numpy as np
import pandas as pd

# Pandas DataFrame

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Data/diamonds.csv")
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [ ]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [ ]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
carat,53940.0,0.797940,0.474011,0.2,0.40,0.70,1.04,5.01
depth,53940.0,61.749405,1.432621,43.0,61.00,61.80,62.50,79.00
table,53940.0,57.457184,2.234491,43.0,56.00,57.00,59.00,95.00
price,53940.0,3932.799722,3989.439738,326.0,950.00,2401.00,5324.25,18823.00
x,53940.0,5.731157,1.121761,0.0,4.71,5.70,6.54,10.74
y,53940.0,5.734526,1.142135,0.0,4.72,5.71,6.54,58.90
z,53940.0,3.538734,0.705699,0.0,2.91,3.53,4.04,31.80

# Groupby

In [ ]:
df.groupby('color').median()

       carat  depth  table   price     x     y     z
color
D       0.53   61.8   57.0  1838.0  5.23  5.24  3.22
E       0.53   61.8   57.0  1739.0  5.23  5.24  3.22
F       0.70   61.8   57.0  2343.5  5.65  5.65  3.48
G       0.70   61.8   57.0  2242.0  5.64  5.63  3.48
H       0.90   61.9   57.0  3460.0  6.14  6.14  3.82
I       1.00   61.9   57.0  3730.0  6.35  6.35  3.93
J       1.11   62.0   58.0  4234.0  6.64  6.63  4.11

In [ ]:
df.groupby('color').mean().sort_index(ascending=False)

,carat,depth,table,price,x,y,z
color,,,,,,,
J,1.162137,61.887215,57.812393,5323.818020,6.519338,6.518105,4.033251
I,1.026927,61.846385,57.577278,5091.874954,6.222826,6.222730,3.845411
H,0.911799,61.836850,57.517811,4486.669196,5.983335,5.984815,3.695965
G,0.771190,61.757111,57.288629,3999.135671,5.677543,5.680192,3.505021
F,0.736538,61.694582,57.433536,3724.886397,5.614961,5.619456,3.464446
E,0.657867,61.662090,57.491201,3076.752475,5.411580,5.419029,3.340689
D,0.657795,61.698125,57.404590,3169.954096,5.417051,5.421128,3.342827

In [ ]:
df.groupby('color').mean().sort_values(by='carat',ascending=True)

,carat,depth,table,price,x,y,z
color,,,,,,,
D,0.657795,61.698125,57.404590,3169.954096,5.417051,5.421128,3.342827
E,0.657867,61.662090,57.491201,3076.752475,5.411580,5.419029,3.340689
F,0.736538,61.694582,57.433536,3724.886397,5.614961,5.619456,3.464446
G,0.771190,61.757111,57.288629,3999.135671,5.677543,5.680192,3.505021
H,0.911799,61.836850,57.517811,4486.669196,5.983335,5.984815,3.695965
I,1.026927,61.846385,57.577278,5091.874954,6.222826,6.222730,3.845411
J,1.162137,61.887215,57.812393,5323.818020,6.519338,6.518105,4.033251

In [ ]:
df.groupby('cut').max()[['depth']]

           depth
cut
Fair        79.0
Good        67.0
Ideal       66.7
Premium     63.0
Very Good   64.9

In [ ]:
df.groupby('cut').max()[['depth']].sort_index(ascending=False)

           depth
cut
Very Good   64.9
Premium     63.0
Ideal       66.7
Good        67.0
Fair        79.0

In [ ]:
df.groupby('cut').max()[['depth']].sort_values(by='depth',ascending=False)

           depth
cut
Fair        79.0
Good        67.0
Ideal       66.7
Very Good   64.9
Premium     63.0

In [ ]:
df.groupby('cut').describe()[['depth']]

             depth
             count       mean       std   min   25%   50%   75%   max
cut
Fair        1610.0  64.041677  3.643428  43.0  64.4  65.0  65.9  79.0
Good        4906.0  62.365879  2.169374  54.3  61.3  63.4  63.8  67.0
Ideal      21551.0  61.709401  0.718539  43.0  61.3  61.8  62.2  66.7
Premium    13791.0  61.264673  1.158815  58.0  60.5  61.4  62.2  63.0
Very Good  12082.0  61.818275  1.378631  56.8  60.9  62.1  62.9  64.9

In [ ]:
df.groupby('cut').describe()[['depth']].transpose()

cut                 Fair         Good         Ideal       Premium  \
depth count  1610.000000  4906.000000  21551.000000  13791.000000
      mean     64.041677    62.365879     61.709401     61.264673
      std       3.643428     2.169374      0.718539      1.158815
      min      43.000000    54.300000     43.000000     58.000000
      25%      64.400000    61.300000     61.300000     60.500000
      50%      65.000000    63.400000     61.800000     61.400000
      75%      65.900000    63.800000     62.200000     62.200000
      max      79.000000    67.000000     66.700000     63.000000

cut             Very Good
depth count  12082.000000
      mean      61.818275
      std        1.378631
      min       56.800000
      25%       60.900000
      50%       62.100000
      75%       62.900000
      max       64.900000

# Aggregate Functions

<table><td><tt
><span
>count</span></tt></td><td>Number of non-null observations</td></tr><tr
><td><tt
><span
>sum</span></tt></td><td>Sum of values</td></tr><tr
><td><tt
><span
>mean</span></tt></td><td>Mean of values</td></tr><tr
><td><tt
><span
>mad</span></tt></td><td>Mean absolute deviation</td></tr><tr
><td><tt
><span
>median</span></tt></td><td>Arithmetic median of values</td></tr><tr
><td><tt
><span
>min</span></tt></td><td>Minimum</td></tr><tr
><td><tt
><span
>max</span></tt></td><td>Maximum</td></tr><tr
><td><tt
><span
>mode</span></tt></td><td>Mode</td></tr><tr
><td><tt
><span
>abs</span></tt></td><td>Absolute Value</td></tr><tr
><td><tt
><span
>prod</span></tt></td><td>Product of values</td></tr><tr
><td><tt
><span
>std</span></tt></td><td>Unbiased standard deviation</td></tr><tr
><td><tt
><span
>var</span></tt></td><td>Unbiased variance</td></tr><tr
><td><tt
><span
>sem</span></tt></td><td>Unbiased standard error of the mean</td></tr><tr
><td><tt
><span
>skew</span></tt></td><td>Unbiased skewness (3rd moment)</td></tr><tr
><td><tt
><span
>kurt</span></tt></td><td>Unbiased kurtosis (4th moment)</td></tr><tr
><td><tt
><span
>quantile</span></tt></td><td>Sample quantile (value at %)</td></tr><tr
><td><tt
><span
>cumsum</span></tt></td><td>Cumulative sum</td></tr><tr
><td><tt
><span
>cumprod</span></tt></td><td>Cumulative product</td></tr><tr
><td><tt
><span
>cummax</span></tt></td><td>Cumulative maximum</td></tr><tr
><td><tt
><span
>cummin</span></tt></td><td>Cumulative minimum</td></tr></tbody></table>

# Miscellaneous

In [ ]:
df['color'].unique()

array(['E', 'I', 'J', 'H', 'F', 'G', 'D'], dtype=object)

In [ ]:
df['color'].nunique()

7

In [ ]:
df.nunique()

carat       214
cut           5
color         7
clarity       8
depth       124
table        70
price      3441
x           476
y           474
z           308
dtype: int64

In [ ]:
df.select_dtypes(include='object').nunique()

cut        5
color      7
clarity    8
dtype: int64

In [ ]:
df['color'].value_counts()

G    1138
F     984
E     938
H     831
D     683
I     552
J     268
Name: color, dtype: int64

In [ ]:
df.groupby('color').count().iloc[:,0].sort_values(ascending=False)

color
G    1138
F     984
E     938
H     831
D     683
I     552
J     268
Name: carat, dtype: int64

In [ ]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

# Handling very large datasets

In [ ]:
#this command is used for very large datasets
#reduces number of rows by selecting random rows
#in this example 10% are selected
df=df.sample(frac=0.1, random_state=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5394 entries, 2714 to 5910
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    5394 non-null   float64
 1   cut      5394 non-null   object
 2   color    5394 non-null   object
 3   clarity  5394 non-null   object
 4   depth    5394 non-null   float64
 5   table    5394 non-null   float64
 6   price    5394 non-null   int64
 7   x        5394 non-null   float64
 8   y        5394 non-null   float64
 9   z        5394 non-null   float64
dtypes: float64(6), int64(1), object(3)
memory usage: 463.5+ KB